version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - production-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - production-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  production-network:
    driver: bridge