name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-formatting:
    name: Code style check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '-skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Run fmt test
      uses: actions-rs/cargo@v1.0.1
      with:
        command: fmt
        args: -- --check
  build:
    name: Build check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
